/*
 * Virus App
 * Datum laatste versie: 31 januari 2018
 * Functionaliteit: Het weergeven, sorteren en filteren van viruslijsten uit 
 * tsv-bestanden van Virus-Host DB en het bepalen van de overlap tussen deze 
 * lijsten. Specifiek ftp://ftp.genome.jp/pub/db/virushostdb/virushostdb.tsv
 */
package virusapplicatie;

/**
 * GUI-class met de aanroep van methoden bij het uitvoeren van bepaalde acties.
 * 
 * @author Jonathan Feenstra
 * @since JDK 1.8
 * @version 1.0
 */
public class VirusGUI extends javax.swing.JFrame {

    /**
     * Creates new form VirusGUI
     */
    public VirusGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortingButtonGroup = new javax.swing.ButtonGroup();
        headerLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        headerSeparator = new javax.swing.JSeparator();
        fileLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        classLabel = new javax.swing.JLabel();
        classComboBox = new javax.swing.JComboBox<>();
        hostLabel = new javax.swing.JLabel();
        hostComboBox1 = new javax.swing.JComboBox<>();
        hostComboBox2 = new javax.swing.JComboBox<>();
        sortPanel = new javax.swing.JPanel();
        idRadioButton = new javax.swing.JRadioButton();
        classRadioButton = new javax.swing.JRadioButton();
        hostsRadioButton = new javax.swing.JRadioButton();
        virusScrollPane1 = new javax.swing.JScrollPane();
        virusTextArea1 = new javax.swing.JTextArea();
        virusScrollPane2 = new javax.swing.JScrollPane();
        virusTextArea2 = new javax.swing.JTextArea();
        overlapScrollPane = new javax.swing.JScrollPane();
        overlapTextArea = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Virus App - © Jonathan Feenstra");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/virusicon.png")).getImage());
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(750, 580));
        setResizable(false);

        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/header.png"))); // NOI18N
        headerLabel.setFocusable(false);
        headerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(headerLabel, java.awt.BorderLayout.PAGE_START);

        fileLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fileLabel.setText("File of URL");

        searchTextField.setText("Search");
        searchTextField.setMaximumSize(new java.awt.Dimension(39, 20));
        searchTextField.setMinimumSize(new java.awt.Dimension(39, 20));
        searchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusLost(evt);
            }
        });

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        searchButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        classLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        classLabel.setText("Viral Classification");

        classComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(VirusLogica.CLASSIFICATIES));
        classComboBox.setMaximumSize(new java.awt.Dimension(159, 20));
        classComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                classComboBoxItemStateChanged(evt);
            }
        });

        hostLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hostLabel.setText("Host ID");

        hostComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<open file to select>" }));
        hostComboBox1.setEnabled(false);
        hostComboBox1.setMaximumSize(new java.awt.Dimension(126, 20));
        hostComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hostComboBox1ItemStateChanged(evt);
            }
        });

        hostComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<open file to select>" }));
        hostComboBox2.setEnabled(false);
        hostComboBox2.setMaximumSize(new java.awt.Dimension(126, 20));
        hostComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hostComboBox2ItemStateChanged(evt);
            }
        });

        sortPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sortering"));

        sortingButtonGroup.add(idRadioButton);
        idRadioButton.setSelected(true);
        idRadioButton.setText("Id");
        idRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idRadioButtonActionPerformed(evt);
            }
        });

        sortingButtonGroup.add(classRadioButton);
        classRadioButton.setText("Classificatie");
        classRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classRadioButtonActionPerformed(evt);
            }
        });

        sortingButtonGroup.add(hostsRadioButton);
        hostsRadioButton.setText("Aantal hosts");
        hostsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostsRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sortPanelLayout = new javax.swing.GroupLayout(sortPanel);
        sortPanel.setLayout(sortPanelLayout);
        sortPanelLayout.setHorizontalGroup(
            sortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(classRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hostsRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sortPanelLayout.setVerticalGroup(
            sortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortPanelLayout.createSequentialGroup()
                .addComponent(idRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hostsRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        virusScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Viruslijst"));

        virusTextArea1.setColumns(20);
        virusTextArea1.setRows(5);
        virusTextArea1.setMaximumSize(new java.awt.Dimension(164, 94));
        virusTextArea1.setMinimumSize(new java.awt.Dimension(164, 94));
        virusScrollPane1.setViewportView(virusTextArea1);

        virusScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Viruslijst"));

        virusTextArea2.setColumns(20);
        virusTextArea2.setRows(5);
        virusTextArea2.setMaximumSize(new java.awt.Dimension(280, 50));
        virusScrollPane2.setViewportView(virusTextArea2);

        overlapScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Overeenkomst"));

        overlapTextArea.setColumns(20);
        overlapTextArea.setRows(5);
        overlapScrollPane.setViewportView(overlapTextArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerSeparator)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(sortPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(virusScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(classLabel)
                            .addComponent(fileLabel)
                            .addComponent(hostLabel))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(searchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton))
                            .addComponent(classComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(hostComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hostComboBox2, 0, 280, Short.MAX_VALUE)
                                    .addComponent(virusScrollPane2)))))
                    .addComponent(overlapScrollPane))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headerSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileLabel)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classLabel)
                    .addComponent(classComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostLabel)
                    .addComponent(hostComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(virusScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(sortPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(virusScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overlapScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open.png"))); // NOI18N
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        VirusLogica.loadFile(evt);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        VirusLogica.loadFile(evt);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void searchTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusGained
        if (searchTextField.getText().equals("Search")) {
            searchTextField.setText("");
        }
    }//GEN-LAST:event_searchTextFieldFocusGained

    private void searchTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusLost
        if (searchTextField.getText().isEmpty()) {
            searchTextField.setText("Search");
        }
    }//GEN-LAST:event_searchTextFieldFocusLost

    private void hostComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hostComboBox1ItemStateChanged
        hostComboBox1.setToolTipText((String) hostComboBox1.getSelectedItem());
        VirusLogica.updateLists();
        VirusLogica.updateTextArea(virusTextArea1, VirusLogica.virusList1);
        VirusLogica.updateTextArea(overlapTextArea, VirusLogica.overlapList);
    }//GEN-LAST:event_hostComboBox1ItemStateChanged

    private void idRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idRadioButtonActionPerformed
        Virus.sortMethod = 0;
        VirusLogica.updateAll();
    }//GEN-LAST:event_idRadioButtonActionPerformed

    private void classRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classRadioButtonActionPerformed
        Virus.sortMethod = 1;
        VirusLogica.updateAll();
    }//GEN-LAST:event_classRadioButtonActionPerformed

    private void hostsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostsRadioButtonActionPerformed
        Virus.sortMethod = 2;
        VirusLogica.updateAll();
    }//GEN-LAST:event_hostsRadioButtonActionPerformed

    private void hostComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hostComboBox2ItemStateChanged
        hostComboBox1.setToolTipText((String) hostComboBox1.getSelectedItem());
        VirusLogica.updateLists();
        VirusLogica.updateTextArea(virusTextArea2, VirusLogica.virusList2);
        VirusLogica.updateTextArea(overlapTextArea, VirusLogica.overlapList);
    }//GEN-LAST:event_hostComboBox2ItemStateChanged

    private void classComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_classComboBoxItemStateChanged
        VirusLogica.updateAll();
    }//GEN-LAST:event_classComboBoxItemStateChanged

    /**
     * Maakt de GUI zichtbaar.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VirusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VirusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VirusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VirusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VirusGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    static javax.swing.JComboBox<String> classComboBox;
    private javax.swing.JLabel classLabel;
    private javax.swing.JRadioButton classRadioButton;
    private javax.swing.JLabel fileLabel;
    static javax.swing.JMenu fileMenu;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JSeparator headerSeparator;
    static javax.swing.JComboBox<String> hostComboBox1;
    static javax.swing.JComboBox<String> hostComboBox2;
    private javax.swing.JLabel hostLabel;
    private javax.swing.JRadioButton hostsRadioButton;
    private javax.swing.JRadioButton idRadioButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    static javax.swing.JMenuItem openMenuItem;
    private javax.swing.JScrollPane overlapScrollPane;
    static javax.swing.JTextArea overlapTextArea;
    static javax.swing.JButton searchButton;
    static javax.swing.JTextField searchTextField;
    private javax.swing.JPanel sortPanel;
    private javax.swing.ButtonGroup sortingButtonGroup;
    private javax.swing.JScrollPane virusScrollPane1;
    private javax.swing.JScrollPane virusScrollPane2;
    static javax.swing.JTextArea virusTextArea1;
    static javax.swing.JTextArea virusTextArea2;
    // End of variables declaration//GEN-END:variables
}
